[package]
name = "cpux"
version = "0.1.6"
authors = ["eckso"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
fern = "0.6.0"
log = "0.4.11"
structopt = "0.3.20"
tabular = "0.1.4"
thiserror = "1.0.22"
